export const SET_FILES_LIST = "SET_FILES_LIST";
export const PUSH_TO_FILES_LIST = "PUSH_TO_FILES_LIST";
export const SET_FILES_LOADING = "SET_FILES_LOADING";
export const SET_FILES_LOADED = "SET_FILES_LOADED";
export const SET_FILES_DIRECTORY = "SET_FILES_DIRECTORY";
export const DELETE_FILE = "DELETE_FILE";
