export const SET_NODES_LIST = "SET_NODES_LIST";
export const PUSH_TO_NODES_LIST = "PUSH_TO_NODES_LIST";
export const SET_NODES_LOADING = "SET_NODES_LOADING";
export const SET_NODES_LOADED = "SET_NODES_LOADED";
